---
jobs:
  - name: test
    public: true
    plan:
      - in_parallel:
        - get: gnatsd
          trigger: true
        - get: daily
          trigger: true
      - task: test
        file: gnatsd/ci/tasks/test.yml

  - name: build
    public: true
    plan:
      - in_parallel:
        - get: gnatsd
          trigger: true
          passed: [ test ]
        - get: version
          params:
            pre: bosh
      - put: version
        params: {file: version/version}
      - in_parallel:
        - task: build-linux
          file: gnatsd/ci/tasks/build-linux.yml
        - task: build-darwin
          file: gnatsd/ci/tasks/build-darwin.yml

      - in_parallel:
        - {put: release-bucket-linux, params: {file: compiled-linux/gnatsd-*-linux-amd64}}
        - {put: release-bucket-darwin, params: {file: compiled-darwin/gnatsd-*-darwin-amd64}}

resources:
  - name: version
    type: semver
    source:
      initial_version: 0.9.6-bosh.10
      key: gnatsd-version
      access_key_id: {{bosh_gnatsd_bucket_access_key_id}}
      secret_access_key: {{bosh_gnatsd_bucket_secret_key}}
      bucket: {{bosh_gnatsd_bucket}}

  - name: gnatsd
    type: git
    source:
      uri: https://github.com/bosh-dep-forks/gnatsd.git
      branch: bosh-1.3.0

  - name: release-bucket-linux
    type: s3
    source:
      regexp: gnatsd-(.*)-linux-amd64
      access_key_id: {{bosh_gnatsd_bucket_access_key_id}}
      secret_access_key: {{bosh_gnatsd_bucket_secret_key}}
      bucket: {{bosh_gnatsd_bucket}}

  - name: release-bucket-darwin
    type: s3
    source:
      regexp: gnatsd-(.*)-darwin-amd64
      access_key_id: {{bosh_gnatsd_bucket_access_key_id}}
      secret_access_key: {{bosh_gnatsd_bucket_secret_key}}
      bucket: {{bosh_gnatsd_bucket}}

  - name: daily
    type: time
    source:
      interval: 24h
